In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

import numpy as np
import matplotlib.pyplot as plt

digits = load_digits()

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

### Logistic Regression

In [5]:
lr = LogisticRegression(solver = 'liblinear', multi_class = 'ovr')

lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9666666666666667

### SVM

In [6]:
svm = SVC(gamma="auto")

svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.3333333333333333

### Random Forest

In [7]:
rf = RandomForestClassifier(n_estimators=40)

rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9722222222222222

## KFOLD Cross Validation

### Basic example

In [10]:
from sklearn.model_selection import KFold

kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


### Use KFold for our digits example

In [12]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)


In [13]:
from sklearn.model_selection import StratifiedKFold

folds = StratifiedKFold(n_splits = 3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train , y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear', multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma="auto"), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [14]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [15]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [16]:
scores_rf

[0.9482470784641068, 0.9482470784641068, 0.9248747913188647]

## Cross_val_score function

In [17]:
from sklearn.model_selection import cross_val_score

### Logistic regression model performance using cross_val_score

In [18]:
cross_val_score(LogisticRegression(solver="liblinear", multi_class="ovr"), digits.data, digits.target, cv=3)

array([0.89482471, 0.95325543, 0.90984975])

### svm model performance using cross_val_score

In [21]:
cross_val_score(SVC(gamma="auto"), digits.data, digits.target, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

### random forest performance using cross_val_score

In [22]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)

array([0.92320534, 0.93989983, 0.92654424])

## Parameter tuning using k fold cross validation

In [25]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target, cv=10)
np.average(scores1)

0.8781440099317195

In [26]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=10)
np.average(scores2)

0.9404531346989448

In [27]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target, cv=10)
np.average(scores3)

0.9398820608317816

In [28]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=10)
np.average(scores4)

0.9460086902545003

## Exercise

In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd

In [5]:
iris = load_iris()

### Logistic Regression

In [6]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

C:\Users\pradeep\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [7]:
np.average(l_scores)

0.9733333333333334

### Decision tree

In [8]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [9]:
np.average(d_scores)

0.9666666666666668

### Support Vector Machine (SVM)

In [10]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [11]:
np.average(s_scores)

0.9666666666666666

### Random Forest

In [12]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [13]:
np.average(r_scores)

0.9666666666666668

## Best score so far Logistic Regression